// AUTO-GENERATED by scripts/analyze-cast-clips.mjs — do not edit by hand.
// Re-run with `npm run analyze:sounds` after changing the cast clips.
//
// Each wizard cast clip is a single file containing both the spell's cast and its
// impact sfx. Measured offline (silence-trimmed RMS-flux transient detection), in
// absolute seconds from the clip's start so its trailing padding can't skew them.
//
//  - CAST_END:   the cast→hit boundary (where the impact transient begins).
//  - CAST_TOTAL: the full cast+hit duration (end of audible content). The engine
//                times the bolt to land here — flight = min(CAST_TOTAL, dur) — so
//                the whole cast+hit clip has played by the moment it connects.
export const CAST_END: Record<string, number> = {
  'cast_air_1': 1.654,
  'cast_air_2': 1.704,
  'cast_air_3': 1.022,
  'cast_air_4': 1.674,
  'cast_blood_1': 1.959,
  'cast_blood_2': 1.052,
  'cast_blood_3': 1.042,
  'cast_blood_4': 1.027,
  'cast_earth_1': 0.877,
  'cast_earth_2': 0.987,
  'cast_earth_3': 0.982,
  'cast_earth_4': 0.997,
  'cast_fire_1': 1.704,
  'cast_fire_2': 1.774,
  'cast_fire_3': 1.724,
  'cast_fire_4': 1.704,
  'cast_ice_1': 1.689,
  'cast_ice_2': 1.679,
  'cast_ice_3': 2.486,
  'cast_ice_4': 0.862,
  'cast_shadow_1': 0.772,
  'cast_shadow_2': 0.832,
  'cast_shadow_3': 0.802,
  'cast_shadow_4': 1.037,
  'cast_smoke_1': 0.897,
  'cast_smoke_2': 0.917,
  'cast_smoke_3': 0.902,
  'cast_water_1': 1.072,
  'cast_water_2': 1.062,
  'cast_water_3': 1.739,
  'cast_water_4': 1.779,
};

export const CAST_TOTAL: Record<string, number> = {
  'cast_air_1': 1.834,
  'cast_air_2': 2.33,
  'cast_air_3': 2.551,
  'cast_air_4': 2.1,
  'cast_blood_1': 3.182,
  'cast_blood_2': 2.746,
  'cast_blood_3': 2.952,
  'cast_blood_4': 2.751,
  'cast_earth_1': 2.471,
  'cast_earth_2': 2.751,
  'cast_earth_3': 2.606,
  'cast_earth_4': 2.581,
  'cast_fire_1': 2.305,
  'cast_fire_2': 2.355,
  'cast_fire_3': 2.496,
  'cast_fire_4': 2.415,
  'cast_ice_1': 2.205,
  'cast_ice_2': 2.375,
  'cast_ice_3': 4.24,
  'cast_ice_4': 4.31,
  'cast_shadow_1': 2.636,
  'cast_shadow_2': 3.708,
  'cast_shadow_3': 2.265,
  'cast_shadow_4': 3.889,
  'cast_smoke_1': 2.1,
  'cast_smoke_2': 2.666,
  'cast_smoke_3': 2.085,
  'cast_water_1': 2.385,
  'cast_water_2': 2.43,
  'cast_water_3': 2.42,
  'cast_water_4': 2.18,
};

/** Fallback fraction for clips without a measurement (≈ the old `dur - dur/4.5`). */
export const DEFAULT_CAST_FRAC = 1 - 1 / 4.5;
