// AUTO-GENERATED by scripts/analyze-cast-clips.mjs — do not edit by hand.
// Re-run with `npm run analyze:sounds` after changing the cast clips.
//
// Each wizard cast clip is a single file containing both the spell's cast and its
// impact sfx. This maps a cast-clip sound key to the absolute time (seconds) of
// the cast→hit boundary, measured by detecting the impact transient offline. The
// engine times the projectile so it lands right then: flight = min(castEnd, dur).
// Absolute seconds (not a fraction) so the clips' trailing silence can't skew it.
export const CAST_END: Record<string, number> = {
  'cast_air_1': 1.654,
  'cast_air_2': 1.704,
  'cast_air_3': 1.022,
  'cast_air_4': 1.674,
  'cast_blood_1': 1.959,
  'cast_blood_2': 1.052,
  'cast_blood_3': 1.042,
  'cast_blood_4': 1.027,
  'cast_earth_1': 0.877,
  'cast_earth_2': 0.987,
  'cast_earth_3': 0.982,
  'cast_earth_4': 0.997,
  'cast_fire_1': 1.704,
  'cast_fire_2': 1.774,
  'cast_fire_3': 1.724,
  'cast_fire_4': 1.704,
  'cast_ice_1': 1.689,
  'cast_ice_2': 1.679,
  'cast_ice_3': 2.486,
  'cast_ice_4': 0.862,
  'cast_shadow_1': 0.772,
  'cast_shadow_2': 0.832,
  'cast_shadow_3': 0.802,
  'cast_shadow_4': 1.037,
  'cast_smoke_1': 0.897,
  'cast_smoke_2': 0.917,
  'cast_smoke_3': 0.902,
  'cast_water_1': 1.072,
  'cast_water_2': 1.062,
  'cast_water_3': 1.739,
  'cast_water_4': 1.779,
};

/** Fallback fraction for clips without a reliable measurement (≈ the old `dur - dur/4.5`). */
export const DEFAULT_CAST_FRAC = 1 - 1 / 4.5;
