// AUTO-GENERATED by scripts/bake-enemy-sprites-from-gltf.mjs + scripts/generate-enemy-anims-data.mjs.
// Do not edit by hand — re-bake and regenerate. 10 diversions, 60 clips.
// Per-view animation sheets baked from the OSRS cache: one loop per camera yaw, so
// a walker can face the way it is going. See lib/game/data/diversion-anims.ts for the
// contract; playback reuses the enemy helpers.
import type { DiversionAnimSet } from './diversion-anims';

const B = `${process.env.NEXT_PUBLIC_BASE_PATH || ''}/assets/diversions`;

export const DIVERSION_ANIMS: Record<string, DiversionAnimSet> = {
  hans: {
    frameW: 128, frameH: 128, worldCell: 226,
    views: {
      front: {
        stand: { url: `${B}/hans/front-stand.png?v=345c08c2`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/front-walk.png?v=9f978918`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/hans/side-stand.png?v=da3c1639`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/side-walk.png?v=d19a1ddd`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/hans/back-stand.png?v=24b216ed`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/back-walk.png?v=e6c4e6c9`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  hunting_expert: {
    frameW: 128, frameH: 128, worldCell: 228,
    views: {
      front: {
        stand: { url: `${B}/hunting_expert/front-stand.png?v=9fbc4c12`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hunting_expert/front-walk.png?v=03fc6247`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/hunting_expert/side-stand.png?v=da67fa23`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hunting_expert/side-walk.png?v=eceb5389`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/hunting_expert/back-stand.png?v=cf745ba9`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hunting_expert/back-walk.png?v=afc8ce58`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  lumbridge_guide: {
    frameW: 128, frameH: 128, worldCell: 285,
    views: {
      front: {
        stand: { url: `${B}/lumbridge_guide/front-stand.png?v=8b7da1ac`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/front-walk.png?v=8609013a`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/lumbridge_guide/side-stand.png?v=504f23ed`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/side-walk.png?v=f4e51360`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/lumbridge_guide/back-stand.png?v=5e0cf02a`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/back-walk.png?v=bdc414ad`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  party_pete: {
    frameW: 128, frameH: 128, worldCell: 241,
    views: {
      front: {
        stand: { url: `${B}/party_pete/front-stand.png?v=f1aaaf4b`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/front-walk.png?v=c2b915d8`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        dance: { url: `${B}/party_pete/front-dance.png?v=9f0cc575`, frames: 215, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 16, 16, 16, 16, 16, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/party_pete/side-stand.png?v=24261c9b`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/side-walk.png?v=25d02599`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        dance: { url: `${B}/party_pete/side-dance.png?v=55afc60e`, frames: 215, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 16, 16, 16, 16, 16, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/party_pete/back-stand.png?v=f3631e80`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/back-walk.png?v=08b1376d`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        dance: { url: `${B}/party_pete/back-dance.png?v=b4073bfe`, frames: 215, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 16, 16, 16, 16, 16, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20], loop: true },
      },
    },
  },
  drunken_dwarf: {
    frameW: 128, frameH: 128, worldCell: 175,
    views: {
      front: {
        stand: { url: `${B}/drunken_dwarf/front-stand.png?v=f9b20f12`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/front-walk.png?v=d40f9d39`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
      side: {
        stand: { url: `${B}/drunken_dwarf/side-stand.png?v=3a3b95d5`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/side-walk.png?v=37381a5f`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
      back: {
        stand: { url: `${B}/drunken_dwarf/back-stand.png?v=9dcfe606`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/back-walk.png?v=738a0c92`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
    },
  },
  genie: {
    frameW: 128, frameH: 128, worldCell: 234,
    views: {
      front: {
        stand: { url: `${B}/genie/front-stand.png?v=95ef0d8c`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/genie/front-walk.png?v=95ef0d8c`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/genie/side-stand.png?v=2fb35add`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/genie/side-walk.png?v=2fb35add`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/genie/back-stand.png?v=386e216c`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/genie/back-walk.png?v=386e216c`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  strange_plant: {
    frameW: 128, frameH: 128, worldCell: 190,
    views: {
      front: {
        stand: { url: `${B}/strange_plant/front-stand.png?v=c9f2549e`, frames: 13, frameMs: [400, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 400], loop: true },
      },
      side: {
        stand: { url: `${B}/strange_plant/side-stand.png?v=ca1c6cca`, frames: 13, frameMs: [400, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 400], loop: true },
      },
      back: {
        stand: { url: `${B}/strange_plant/back-stand.png?v=70de88d8`, frames: 13, frameMs: [400, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 400], loop: true },
      },
    },
  },
  sergeant_damien: {
    frameW: 128, frameH: 128, worldCell: 284,
    views: {
      front: {
        stand: { url: `${B}/sergeant_damien/front-stand.png?v=3bcf67cc`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/sergeant_damien/front-walk.png?v=1ba2aeda`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/sergeant_damien/side-stand.png?v=0ab9d97f`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/sergeant_damien/side-walk.png?v=752fe7a2`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/sergeant_damien/back-stand.png?v=9fafef6b`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/sergeant_damien/back-walk.png?v=84657547`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  dr_jekyll: {
    frameW: 128, frameH: 128, worldCell: 227,
    views: {
      front: {
        stand: { url: `${B}/dr_jekyll/front-stand.png?v=2b2383c6`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/dr_jekyll/front-walk.png?v=aecb2059`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/dr_jekyll/side-stand.png?v=7727dc48`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/dr_jekyll/side-walk.png?v=ca13f221`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/dr_jekyll/back-stand.png?v=3f95d1a9`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/dr_jekyll/back-walk.png?v=cbfe8a34`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  tool_leprechaun: {
    frameW: 128, frameH: 128, worldCell: 171,
    views: {
      front: {
        stand: { url: `${B}/tool_leprechaun/front-stand.png?v=be0ee9b4`, frames: 30, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 320, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/tool_leprechaun/front-walk.png?v=910d4097`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
      side: {
        stand: { url: `${B}/tool_leprechaun/side-stand.png?v=b1d89719`, frames: 30, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 320, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/tool_leprechaun/side-walk.png?v=3ec8f8cd`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
      back: {
        stand: { url: `${B}/tool_leprechaun/back-stand.png?v=869c88e9`, frames: 30, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 320, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/tool_leprechaun/back-walk.png?v=0fbc95ed`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
    },
  },
};
