// AUTO-GENERATED by scripts/bake-enemy-sprites-from-gltf.mjs + scripts/generate-enemy-anims-data.mjs.
// Do not edit by hand — re-bake and regenerate. 10 diversions, 60 clips.
// Per-view animation sheets baked from the OSRS cache: one loop per camera yaw, so
// a walker can face the way it is going. See lib/game/data/diversion-anims.ts for the
// contract; playback reuses the enemy helpers.
import type { DiversionAnimSet } from './diversion-anims';

const B = `${process.env.NEXT_PUBLIC_BASE_PATH || ''}/assets/diversions`;

export const DIVERSION_ANIMS: Record<string, DiversionAnimSet> = {
  hans: {
    frameW: 128, frameH: 128, worldCell: 226,
    views: {
      front: {
        stand: { url: `${B}/hans/front-stand.png?v=1624cdab`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/front-walk.png?v=26541f55`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/hans/side-stand.png?v=7fc26773`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/side-walk.png?v=4999e66c`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/hans/back-stand.png?v=ba6397fb`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/back-walk.png?v=2ef83f01`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  hunting_expert: {
    frameW: 128, frameH: 128, worldCell: 228,
    views: {
      front: {
        stand: { url: `${B}/hunting_expert/front-stand.png?v=5e79691b`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hunting_expert/front-walk.png?v=9d71208f`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/hunting_expert/side-stand.png?v=e55f9f0a`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hunting_expert/side-walk.png?v=a233bd8b`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/hunting_expert/back-stand.png?v=b353632a`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hunting_expert/back-walk.png?v=f92667a2`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  lumbridge_guide: {
    frameW: 128, frameH: 128, worldCell: 284,
    views: {
      front: {
        stand: { url: `${B}/lumbridge_guide/front-stand.png?v=9a77bfb1`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/front-walk.png?v=636213a4`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/lumbridge_guide/side-stand.png?v=e0374904`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/side-walk.png?v=8b3391bb`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/lumbridge_guide/back-stand.png?v=2a3461e5`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/back-walk.png?v=5bf41075`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  party_pete: {
    frameW: 128, frameH: 128, worldCell: 241,
    views: {
      front: {
        stand: { url: `${B}/party_pete/front-stand.png?v=0c4b0f06`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/front-walk.png?v=373f168b`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        dance: { url: `${B}/party_pete/front-dance.png?v=c1812569`, frames: 215, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 16, 16, 16, 16, 16, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/party_pete/side-stand.png?v=a21d893f`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/side-walk.png?v=9071108b`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        dance: { url: `${B}/party_pete/side-dance.png?v=ee8909b3`, frames: 215, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 16, 16, 16, 16, 16, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/party_pete/back-stand.png?v=9f9e45fa`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/back-walk.png?v=c9ef23fb`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        dance: { url: `${B}/party_pete/back-dance.png?v=6a666186`, frames: 215, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 16, 16, 16, 16, 16, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 18, 18, 19, 18, 18, 18, 18, 18, 19, 18, 18, 20, 20, 20, 20], loop: true },
      },
    },
  },
  drunken_dwarf: {
    frameW: 128, frameH: 128, worldCell: 175,
    views: {
      front: {
        stand: { url: `${B}/drunken_dwarf/front-stand.png?v=b3615646`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/front-walk.png?v=6b0bbdcb`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
      side: {
        stand: { url: `${B}/drunken_dwarf/side-stand.png?v=b40dbc92`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/side-walk.png?v=9751bd42`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
      back: {
        stand: { url: `${B}/drunken_dwarf/back-stand.png?v=13c8ae58`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/back-walk.png?v=cfee7844`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
    },
  },
  genie: {
    frameW: 128, frameH: 128, worldCell: 234,
    views: {
      front: {
        stand: { url: `${B}/genie/front-stand.png?v=38f5d4c9`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/genie/front-walk.png?v=38f5d4c9`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/genie/side-stand.png?v=9d2d3198`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/genie/side-walk.png?v=9d2d3198`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/genie/back-stand.png?v=dde1111f`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/genie/back-walk.png?v=dde1111f`, frames: 22, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  strange_plant: {
    frameW: 128, frameH: 128, worldCell: 190,
    views: {
      front: {
        stand: { url: `${B}/strange_plant/front-stand.png?v=7a663766`, frames: 13, frameMs: [400, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 400], loop: true },
      },
      side: {
        stand: { url: `${B}/strange_plant/side-stand.png?v=5214ab3f`, frames: 13, frameMs: [400, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 400], loop: true },
      },
      back: {
        stand: { url: `${B}/strange_plant/back-stand.png?v=e87d0e5a`, frames: 13, frameMs: [400, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 400], loop: true },
      },
    },
  },
  sergeant_damien: {
    frameW: 128, frameH: 128, worldCell: 284,
    views: {
      front: {
        stand: { url: `${B}/sergeant_damien/front-stand.png?v=63dc8ecd`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/sergeant_damien/front-walk.png?v=c750c509`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/sergeant_damien/side-stand.png?v=b1b2230f`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/sergeant_damien/side-walk.png?v=0e00d1f9`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/sergeant_damien/back-stand.png?v=b49230f8`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/sergeant_damien/back-walk.png?v=e274d7dc`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  dr_jekyll: {
    frameW: 128, frameH: 128, worldCell: 226,
    views: {
      front: {
        stand: { url: `${B}/dr_jekyll/front-stand.png?v=9f521ea8`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/dr_jekyll/front-walk.png?v=49f120ba`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      side: {
        stand: { url: `${B}/dr_jekyll/side-stand.png?v=d074708c`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/dr_jekyll/side-walk.png?v=f2ef16a6`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
      back: {
        stand: { url: `${B}/dr_jekyll/back-stand.png?v=8723390b`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/dr_jekyll/back-walk.png?v=9fb52a12`, frames: 49, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 17, 17, 18, 17, 17, 17, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
      },
    },
  },
  tool_leprechaun: {
    frameW: 128, frameH: 128, worldCell: 171,
    views: {
      front: {
        stand: { url: `${B}/tool_leprechaun/front-stand.png?v=4fe980db`, frames: 30, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 320, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/tool_leprechaun/front-walk.png?v=79b962db`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
      side: {
        stand: { url: `${B}/tool_leprechaun/side-stand.png?v=d3b4c1b1`, frames: 30, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 320, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/tool_leprechaun/side-walk.png?v=32af11c0`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
      back: {
        stand: { url: `${B}/tool_leprechaun/back-stand.png?v=708e91e2`, frames: 30, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 320, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: true },
        walk: { url: `${B}/tool_leprechaun/back-walk.png?v=f72460aa`, frames: 42, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17, 20, 20, 20, 20, 20, 17, 16, 17, 17, 16, 17], loop: true },
      },
    },
  },
};
