// AUTO-GENERATED by scripts/bake-enemy-sprites-from-gltf.mjs + scripts/generate-enemy-anims-data.mjs.
// Do not edit by hand — re-bake and regenerate. 8 diversions, 45 clips.
// Per-view animation sheets baked from the OSRS cache: one loop per camera yaw, so
// a walker can face the way it is going. See lib/game/data/diversion-anims.ts for the
// contract; playback reuses the enemy helpers.
import type { DiversionAnimSet } from './diversion-anims';

const B = `${process.env.NEXT_PUBLIC_BASE_PATH || ''}/assets/diversions`;

export const DIVERSION_ANIMS: Record<string, DiversionAnimSet> = {
  hans: {
    frameW: 128, frameH: 128,
    views: {
      front: {
        stand: { url: `${B}/hans/front-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/front-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      side: {
        stand: { url: `${B}/hans/side-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/side-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      back: {
        stand: { url: `${B}/hans/back-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/hans/back-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
    },
  },
  bob: {
    frameW: 128, frameH: 128,
    views: {
      front: {
        stand: { url: `${B}/bob/front-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/bob/front-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      side: {
        stand: { url: `${B}/bob/side-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/bob/side-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      back: {
        stand: { url: `${B}/bob/back-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/bob/back-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
    },
  },
  lumbridge_guide: {
    frameW: 128, frameH: 128,
    views: {
      front: {
        stand: { url: `${B}/lumbridge_guide/front-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/front-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      side: {
        stand: { url: `${B}/lumbridge_guide/side-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/side-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      back: {
        stand: { url: `${B}/lumbridge_guide/back-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/lumbridge_guide/back-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
    },
  },
  party_pete: {
    frameW: 128, frameH: 128,
    views: {
      front: {
        stand: { url: `${B}/party_pete/front-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/front-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      side: {
        stand: { url: `${B}/party_pete/side-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/side-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      back: {
        stand: { url: `${B}/party_pete/back-stand.png`, frames: 12, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400, 400], loop: true },
        walk: { url: `${B}/party_pete/back-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
    },
  },
  drunken_dwarf: {
    frameW: 128, frameH: 128,
    views: {
      front: {
        stand: { url: `${B}/drunken_dwarf/front-stand.png`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/front-walk.png`, frames: 15, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      },
      side: {
        stand: { url: `${B}/drunken_dwarf/side-stand.png`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/side-walk.png`, frames: 15, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      },
      back: {
        stand: { url: `${B}/drunken_dwarf/back-stand.png`, frames: 2, frameMs: [400, 400], loop: true },
        walk: { url: `${B}/drunken_dwarf/back-walk.png`, frames: 15, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      },
    },
  },
  genie: {
    frameW: 128, frameH: 128,
    views: {
      front: {
        stand: { url: `${B}/genie/front-stand.png`, frames: 5, frameMs: [220, 55, 55, 55, 55], loop: true },
        walk: { url: `${B}/genie/front-walk.png`, frames: 5, frameMs: [220, 55, 55, 55, 55], loop: true },
      },
      side: {
        stand: { url: `${B}/genie/side-stand.png`, frames: 5, frameMs: [220, 55, 55, 55, 55], loop: true },
        walk: { url: `${B}/genie/side-walk.png`, frames: 5, frameMs: [220, 55, 55, 55, 55], loop: true },
      },
      back: {
        stand: { url: `${B}/genie/back-stand.png`, frames: 5, frameMs: [220, 55, 55, 55, 55], loop: true },
        walk: { url: `${B}/genie/back-walk.png`, frames: 5, frameMs: [220, 55, 55, 55, 55], loop: true },
      },
    },
  },
  strange_plant: {
    frameW: 128, frameH: 128,
    views: {
      front: {
        stand: { url: `${B}/strange_plant/front-stand.png`, frames: 6, frameMs: [400, 55, 55, 55, 55, 400], loop: true },
      },
      side: {
        stand: { url: `${B}/strange_plant/side-stand.png`, frames: 6, frameMs: [400, 55, 55, 55, 55, 400], loop: true },
      },
      back: {
        stand: { url: `${B}/strange_plant/back-stand.png`, frames: 6, frameMs: [400, 55, 55, 55, 55, 400], loop: true },
      },
    },
  },
  rick_turpentine: {
    frameW: 128, frameH: 128,
    views: {
      front: {
        stand: { url: `${B}/rick_turpentine/front-stand.png`, frames: 41, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 60, 60, 60, 60, 60, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
        walk: { url: `${B}/rick_turpentine/front-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      side: {
        stand: { url: `${B}/rick_turpentine/side-stand.png`, frames: 41, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 60, 60, 60, 60, 60, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
        walk: { url: `${B}/rick_turpentine/side-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
      back: {
        stand: { url: `${B}/rick_turpentine/back-stand.png`, frames: 41, frameMs: [400, 400, 400, 400, 400, 400, 400, 400, 60, 60, 60, 60, 60, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
        walk: { url: `${B}/rick_turpentine/back-walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      },
    },
  },
};
