// AUTO-GENERATED by scripts/bake-enemy-sprites-from-gltf.mjs + scripts/generate-enemy-anims-data.mjs.
// Do not edit by hand — re-bake and regenerate. 75 enemies, 218 clips.
// Per-enemy animation sheets baked from the OSRS cache (walk loop + optional
// hurt flinch + death collapse). See lib/game/data/enemy-anims.ts for the
// playback helpers and the EnemyAnimSet contract.
import type { EnemyAnimSet } from './enemy-anims';

const B = `${process.env.NEXT_PUBLIC_BASE_PATH || ''}/assets/enemies`;

export const ENEMY_ANIMS: Record<string, EnemyAnimSet> = {
  goblin: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/goblin/walk.png`, frames: 16, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/goblin/hurt.png`, frames: 37, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/goblin/death.png`, frames: 35, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 60, 30, 30, 60, 30, 30], loop: false },
    },
  },
  rat: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/rat/walk.png`, frames: 16, frameMs: [20, 40, 20, 40, 40, 40, 20, 40, 40, 40, 20, 40, 40, 40, 20, 40], loop: true },
      hurt: { url: `${B}/rat/hurt.png`, frames: 16, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/rat/death.png`, frames: 44, frameMs: [100, 50, 50, 50, 50, 60, 60, 60, 60, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 60, 60, 60, 60, 40, 40, 40, 60, 60], loop: false },
    },
  },
  cow: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/cow/walk.png`, frames: 15, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/cow/hurt.png`, frames: 19, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/cow/death.png`, frames: 38, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 60, 40, 40, 40, 40, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  imp: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/imp/walk.png`, frames: 8, frameMs: [60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/imp/hurt.png`, frames: 16, frameMs: [80, 40, 40, 40, 40, 40, 40, 47, 47, 47, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/imp/death.png`, frames: 16, frameMs: [80, 40, 40, 60, 60, 60, 60, 40, 40, 60, 40, 40, 50, 50, 50, 50], loop: false },
    },
  },
  spider: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/spider/walk.png`, frames: 10, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/spider/hurt.png`, frames: 16, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/spider/death.png`, frames: 25, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 40, 40, 40, 40, 40, 40, 60, 60, 50, 50, 50, 50], loop: false },
    },
  },
  skeleton: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/skeleton/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/skeleton/hurt.png`, frames: 19, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/skeleton/death.png`, frames: 47, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  zombie: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/zombie/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/zombie/hurt.png`, frames: 39, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/zombie/death.png`, frames: 47, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  ghost: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/ghost/walk.png`, frames: 31, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/ghost/hurt.png`, frames: 29, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/ghost/death.png`, frames: 39, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 30, 30, 40, 40, 40, 40, 40, 40, 60, 30], loop: false },
    },
  },
  hellhound: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/hellhound/walk.png`, frames: 31, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/hellhound/hurt.png`, frames: 12, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/hellhound/death.png`, frames: 24, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 50, 50], loop: false },
    },
  },
  scorpion: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/scorpion/walk.png`, frames: 15, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/scorpion/hurt.png`, frames: 16, frameMs: [60, 60, 60, 40, 40, 50, 50, 50, 50, 50, 50, 40, 40, 60, 60, 60], loop: false },
      death: { url: `${B}/scorpion/death.png`, frames: 25, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 47, 47, 47, 60, 60, 40, 40, 60, 50, 50, 50, 50], loop: false },
    },
  },
  fire_giant: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/fire_giant/walk.png`, frames: 19, frameMs: [40, 60, 60, 60, 60, 40, 60, 60, 60, 40, 40, 60, 60, 60, 60, 60, 60, 60, 40], loop: true },
      hurt: { url: `${B}/fire_giant/hurt.png`, frames: 21, frameMs: [20, 40, 40, 60, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 40, 40, 60, 60, 60, 60, 20], loop: false },
      death: { url: `${B}/fire_giant/death.png`, frames: 40, frameMs: [20, 47, 47, 47, 47, 47, 47, 47, 47, 47, 60, 60, 60, 60, 50, 50, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 47, 47, 47, 120], loop: false },
    },
  },
  bloodveld: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/bloodveld/walk.png`, frames: 15, frameMs: [80, 50, 50, 50, 50, 40, 40, 50, 50, 50, 50, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/bloodveld/hurt.png`, frames: 15, frameMs: [60, 40, 40, 50, 50, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/bloodveld/death.png`, frames: 10, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 120], loop: false },
    },
  },
  hill_giant: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/hill_giant/walk.png`, frames: 19, frameMs: [60, 60, 60, 60, 60, 40, 60, 60, 60, 40, 60, 60, 60, 60, 60, 60, 60, 60, 40], loop: true },
      hurt: { url: `${B}/hill_giant/hurt.png`, frames: 21, frameMs: [20, 40, 40, 60, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 40, 40, 60, 60, 60, 60, 20], loop: false },
      death: { url: `${B}/hill_giant/death.png`, frames: 40, frameMs: [20, 47, 47, 47, 47, 47, 47, 47, 47, 47, 60, 60, 60, 60, 50, 50, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 50, 50, 60, 60, 60, 60, 60, 60, 47, 47, 47, 120], loop: false },
    },
  },
  black_demon: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/black_demon/walk.png`, frames: 40, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 53, 53, 53, 40, 40], loop: true },
      hurt: { url: `${B}/black_demon/hurt.png`, frames: 24, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 400, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60], loop: false },
      death: { url: `${B}/black_demon/death.png`, frames: 56, frameMs: [200, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 40, 40, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  gargoyle: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/gargoyle/walk.png`, frames: 17, frameMs: [60, 60, 60, 60, 47, 47, 47, 60, 40, 40, 40, 60, 40, 40, 40, 40, 60], loop: true },
    },
  },
  blue_dragon: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/blue_dragon/walk.png`, frames: 16, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/blue_dragon/hurt.png`, frames: 21, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 400, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/blue_dragon/death.png`, frames: 30, frameMs: [60, 40, 40, 50, 50, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 50, 50, 50, 50], loop: false },
    },
  },
  nechryael: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/nechryael/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/nechryael/hurt.png`, frames: 15, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/nechryael/death.png`, frames: 24, frameMs: [60, 40, 40, 60, 60, 47, 47, 47, 60, 60, 60, 50, 50, 50, 50, 50, 50, 50, 50, 40, 40, 40, 40, 120], loop: false },
    },
  },
  abyssal_demon: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/abyssal_demon/walk.png`, frames: 15, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/abyssal_demon/hurt.png`, frames: 15, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/abyssal_demon/death.png`, frames: 16, frameMs: [80, 60, 60, 50, 50, 47, 47, 47, 47, 47, 47, 60, 60, 60, 60, 120], loop: false },
    },
  },
  lesser_demon: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/lesser_demon/walk.png`, frames: 40, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 53, 53, 53, 40, 40], loop: true },
      hurt: { url: `${B}/lesser_demon/hurt.png`, frames: 24, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 400, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60], loop: false },
      death: { url: `${B}/lesser_demon/death.png`, frames: 56, frameMs: [200, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 40, 40, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  dark_beast: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/dark_beast/walk.png`, frames: 24, frameMs: [60, 40, 40, 60, 40, 40, 60, 40, 40, 60, 40, 40, 60, 40, 40, 60, 40, 40, 60, 40, 40, 60, 40, 40], loop: true },
      hurt: { url: `${B}/dark_beast/hurt.png`, frames: 33, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/dark_beast/death.png`, frames: 74, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 120], loop: false },
    },
  },
  green_dragon: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/green_dragon/walk.png`, frames: 16, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/green_dragon/hurt.png`, frames: 21, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 400, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/green_dragon/death.png`, frames: 30, frameMs: [60, 40, 40, 50, 50, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 50, 50, 50, 50], loop: false },
    },
  },
  jad: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/jad/walk.png`, frames: 46, frameMs: [140, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47], loop: true },
      hurt: { url: `${B}/jad/hurt.png`, frames: 32, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 300, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/jad/death.png`, frames: 46, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 30, 30, 60, 30, 30, 50, 50, 60, 60, 60, 60, 60, 50, 50, 50, 50, 300, 50, 50, 50, 50], loop: false },
    },
  },
  yt_hurkot: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/yt_hurkot/walk.png`, frames: 46, frameMs: [160, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53], loop: true },
      hurt: { url: `${B}/yt_hurkot/hurt.png`, frames: 14, frameMs: [60, 60, 60, 60, 60, 60, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/yt_hurkot/death.png`, frames: 21, frameMs: [100, 40, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 40, 40, 60, 120], loop: false },
    },
  },
  vorkath: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/vorkath/walk.png`, frames: 42, frameMs: [60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 30, 30, 60], loop: true },
      hurt: { url: `${B}/vorkath/hurt.png`, frames: 29, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/vorkath/death.png`, frames: 99, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
    },
  },
  zulrah: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/zulrah/walk.png`, frames: 17, frameMs: [100, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 50, 50, 40, 40, 40, 40], loop: true },
      death: { url: `${B}/zulrah/death.png`, frames: 23, frameMs: [40, 40, 40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30], loop: false },
    },
  },
  barrow_wight: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/barrow_wight/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/barrow_wight/hurt.png`, frames: 14, frameMs: [160, 60, 60, 50, 50, 40, 40, 400, 40, 40, 50, 50, 60, 60], loop: false },
      death: { url: `${B}/barrow_wight/death.png`, frames: 18, frameMs: [160, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  chaos_druid: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/chaos_druid/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/chaos_druid/hurt.png`, frames: 14, frameMs: [160, 60, 60, 50, 50, 40, 40, 400, 40, 40, 50, 50, 60, 60], loop: false },
      death: { url: `${B}/chaos_druid/death.png`, frames: 18, frameMs: [160, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  skeletal_mage: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/skeletal_mage/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/skeletal_mage/hurt.png`, frames: 19, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/skeletal_mage/death.png`, frames: 47, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  hydra: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/hydra/walk.png`, frames: 37, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 40, 40, 40, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 60, 30, 30, 60, 40, 40, 40], loop: true },
      death: { url: `${B}/hydra/death.png`, frames: 56, frameMs: [60, 60, 60, 60, 40, 40, 40, 40, 50, 50, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 60, 30, 30, 60, 60, 60, 30, 30], loop: false },
    },
  },
  superior_bloodveld: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/superior_bloodveld/walk.png`, frames: 15, frameMs: [80, 50, 50, 50, 50, 40, 40, 50, 50, 50, 50, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/superior_bloodveld/hurt.png`, frames: 15, frameMs: [60, 40, 40, 50, 50, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/superior_bloodveld/death.png`, frames: 10, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 120], loop: false },
    },
  },
  superior_abyssal_demon: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/superior_abyssal_demon/walk.png`, frames: 15, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/superior_abyssal_demon/hurt.png`, frames: 15, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/superior_abyssal_demon/death.png`, frames: 16, frameMs: [80, 60, 60, 50, 50, 47, 47, 47, 47, 47, 47, 60, 60, 60, 60, 120], loop: false },
    },
  },
  superior_gargoyle: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/superior_gargoyle/walk.png`, frames: 30, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/superior_gargoyle/hurt.png`, frames: 15, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
    },
  },
  superior_nechryael: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/superior_nechryael/walk.png`, frames: 19, frameMs: [60, 60, 60, 60, 60, 40, 60, 60, 60, 40, 60, 60, 60, 60, 60, 60, 60, 60, 40], loop: true },
      hurt: { url: `${B}/superior_nechryael/hurt.png`, frames: 21, frameMs: [20, 40, 40, 60, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 40, 40, 60, 60, 60, 60, 20], loop: false },
      death: { url: `${B}/superior_nechryael/death.png`, frames: 41, frameMs: [20, 47, 47, 47, 47, 47, 47, 47, 47, 47, 60, 60, 60, 60, 50, 50, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 50, 50, 60, 60, 60, 60, 60, 60, 47, 47, 47, 400, 120], loop: false },
    },
  },
  giant_mole: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/giant_mole/walk.png`, frames: 15, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/giant_mole/hurt.png`, frames: 13, frameMs: [80, 40, 40, 60, 60, 60, 60, 20, 20, 20, 20, 60, 60], loop: false },
      death: { url: `${B}/giant_mole/death.png`, frames: 21, frameMs: [140, 47, 47, 47, 47, 47, 47, 60, 60, 60, 60, 20, 20, 50, 50, 40, 40, 40, 40, 40, 40], loop: false },
      burrow: { url: `${B}/giant_mole/burrow.png`, frames: 38, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 30, 30, 60, 30, 30, 60, 60], loop: false },
      emerge: { url: `${B}/giant_mole/emerge.png`, frames: 17, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  dusk: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/dusk/walk.png`, frames: 30, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/dusk/hurt.png`, frames: 22, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30], loop: false },
    },
  },
  dawn: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/dawn/walk.png`, frames: 27, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 60, 60, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/dawn/hurt.png`, frames: 15, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
    },
  },
  cerberus: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/cerberus/walk.png`, frames: 29, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/cerberus/hurt.png`, frames: 23, frameMs: [140, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 60, 60, 50, 50], loop: false },
      death: { url: `${B}/cerberus/death.png`, frames: 17, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 60, 60, 50, 50, 50, 50], loop: false },
    },
  },
  soul_ranged: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/soul_ranged/walk.png`, frames: 28, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 30, 30, 40, 40], loop: true },
      hurt: { url: `${B}/soul_ranged/hurt.png`, frames: 11, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  soul_magic: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/soul_magic/walk.png`, frames: 28, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 30, 30, 40, 40], loop: true },
      hurt: { url: `${B}/soul_magic/hurt.png`, frames: 11, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  soul_melee: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/soul_melee/walk.png`, frames: 28, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 30, 30, 40, 40], loop: true },
      hurt: { url: `${B}/soul_melee/hurt.png`, frames: 11, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  brutus: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/brutus/walk.png`, frames: 47, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/brutus/hurt.png`, frames: 9, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/brutus/death.png`, frames: 26, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 60, 40, 40, 40, 40, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  brutus_demonic: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/brutus_demonic/walk.png`, frames: 47, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/brutus_demonic/hurt.png`, frames: 9, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/brutus_demonic/death.png`, frames: 26, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 60, 40, 40, 40, 40, 50, 50, 50, 50, 50, 50], loop: false },
      rage: { url: `${B}/brutus_demonic/rage.png`, frames: 41, frameMs: [80, 40, 40, 40, 40, 40, 40, 60, 60, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50], loop: true },
      charge: { url: `${B}/brutus_demonic/charge.png`, frames: 36, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 60, 30, 30, 60, 30, 30, 60], loop: true },
    },
  },
  scurrius: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/scurrius/walk.png`, frames: 37, frameMs: [20, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 40], loop: true },
      death: { url: `${B}/scurrius/death.png`, frames: 63, frameMs: [20, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 60, 60, 30, 30, 60, 60, 60, 30, 30, 60, 60, 60, 30, 30, 60, 60, 60, 30, 30, 60, 40], loop: false },
    },
  },
  ahrim: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/ahrim/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/ahrim/hurt.png`, frames: 14, frameMs: [160, 60, 60, 50, 50, 40, 40, 400, 40, 40, 50, 50, 60, 60], loop: false },
      death: { url: `${B}/ahrim/death.png`, frames: 18, frameMs: [160, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  guthan: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/guthan/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/guthan/hurt.png`, frames: 14, frameMs: [160, 60, 60, 50, 50, 40, 40, 400, 40, 40, 50, 50, 60, 60], loop: false },
      death: { url: `${B}/guthan/death.png`, frames: 18, frameMs: [160, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  karil: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/karil/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/karil/hurt.png`, frames: 14, frameMs: [160, 60, 60, 50, 50, 40, 40, 400, 40, 40, 50, 50, 60, 60], loop: false },
      death: { url: `${B}/karil/death.png`, frames: 18, frameMs: [160, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  torag: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/torag/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/torag/hurt.png`, frames: 14, frameMs: [160, 60, 60, 50, 50, 40, 40, 400, 40, 40, 50, 50, 60, 60], loop: false },
      death: { url: `${B}/torag/death.png`, frames: 18, frameMs: [160, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  verac: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/verac/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/verac/hurt.png`, frames: 14, frameMs: [160, 60, 60, 50, 50, 40, 40, 400, 40, 40, 50, 50, 60, 60], loop: false },
      death: { url: `${B}/verac/death.png`, frames: 18, frameMs: [160, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  ice_warrior: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/ice_warrior/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/ice_warrior/hurt.png`, frames: 14, frameMs: [160, 60, 60, 50, 50, 40, 40, 400, 40, 40, 50, 50, 60, 60], loop: false },
      death: { url: `${B}/ice_warrior/death.png`, frames: 9, frameMs: [160, 40, 40, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  ice_troll: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/ice_troll/walk.png`, frames: 20, frameMs: [160, 47, 47, 47, 47, 47, 47, 50, 50, 53, 53, 53, 47, 47, 47, 47, 47, 47, 50, 50], loop: true },
      hurt: { url: `${B}/ice_troll/hurt.png`, frames: 6, frameMs: [100, 40, 40, 40, 40, 120], loop: false },
      death: { url: `${B}/ice_troll/death.png`, frames: 13, frameMs: [80, 40, 40, 60, 60, 50, 50, 50, 50, 40, 40, 20, 120], loop: false },
    },
  },
  jogre: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/jogre/walk.png`, frames: 25, frameMs: [180, 50, 50, 50, 50, 60, 60, 60, 60, 60, 60, 60, 60, 60, 50, 50, 50, 50, 60, 60, 60, 45, 45, 45, 45], loop: true },
      hurt: { url: `${B}/jogre/hurt.png`, frames: 9, frameMs: [40, 40, 40, 60, 50, 50, 60, 40, 40], loop: false },
      death: { url: `${B}/jogre/death.png`, frames: 18, frameMs: [100, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  harpie_bug_swarm: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/harpie_bug_swarm/walk.png`, frames: 16, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/harpie_bug_swarm/hurt.png`, frames: 16, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20], loop: false },
      death: { url: `${B}/harpie_bug_swarm/death.png`, frames: 7, frameMs: [40, 40, 40, 40, 40, 60, 120], loop: false },
    },
  },
  cave_bug: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/cave_bug/walk.png`, frames: 8, frameMs: [60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/cave_bug/hurt.png`, frames: 19, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30], loop: false },
      death: { url: `${B}/cave_bug/death.png`, frames: 24, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60], loop: false },
    },
  },
  cave_slime: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/cave_slime/walk.png`, frames: 8, frameMs: [60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/cave_slime/hurt.png`, frames: 12, frameMs: [40, 40, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/cave_slime/death.png`, frames: 16, frameMs: [40, 40, 60, 60, 40, 40, 40, 40, 40, 40, 60, 60, 40, 60, 60, 120], loop: false },
    },
  },
  big_frog: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/big_frog/walk.png`, frames: 8, frameMs: [140, 60, 50, 50, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/big_frog/hurt.png`, frames: 13, frameMs: [160, 40, 40, 60, 40, 320, 40, 60, 40, 40, 53, 53, 53], loop: false },
      death: { url: `${B}/big_frog/death.png`, frames: 7, frameMs: [160, 60, 60, 40, 40, 40, 120], loop: false },
    },
  },
  giant_frog: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/giant_frog/walk.png`, frames: 8, frameMs: [140, 60, 50, 50, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/giant_frog/hurt.png`, frames: 13, frameMs: [160, 40, 40, 60, 40, 320, 40, 60, 40, 40, 53, 53, 53], loop: false },
      death: { url: `${B}/giant_frog/death.png`, frames: 7, frameMs: [160, 60, 60, 40, 40, 40, 120], loop: false },
    },
  },
  hobgoblin: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/hobgoblin/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/hobgoblin/hurt.png`, frames: 14, frameMs: [100, 40, 40, 60, 40, 60, 60, 60, 60, 60, 40, 60, 40, 40], loop: false },
      death: { url: `${B}/hobgoblin/death.png`, frames: 12, frameMs: [80, 60, 60, 60, 50, 50, 50, 50, 40, 20, 20, 120], loop: false },
    },
  },
  giant_bat: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/giant_bat/walk.png`, frames: 13, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/giant_bat/hurt.png`, frames: 17, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/giant_bat/death.png`, frames: 36, frameMs: [60, 60, 60, 60, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 400, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 40, 40, 40, 60, 60], loop: false },
    },
  },
  moss_giant: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/moss_giant/walk.png`, frames: 18, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 40, 60, 60, 60, 60, 60, 60, 60, 60, 40], loop: true },
      hurt: { url: `${B}/moss_giant/hurt.png`, frames: 20, frameMs: [20, 40, 40, 60, 40, 40, 40, 40, 60, 60, 50, 50, 50, 50, 40, 40, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/moss_giant/death.png`, frames: 65, frameMs: [40, 50, 50, 50, 50, 50, 50, 50, 50, 60, 60, 53, 53, 53, 60, 60, 60, 45, 45, 45, 45, 60, 60, 60, 45, 45, 45, 45, 60, 60, 60, 60, 60, 60, 45, 45, 45, 45, 45, 45, 45, 45, 60, 60, 60, 45, 45, 45, 45, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  vulture: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/vulture/walk.png`, frames: 8, frameMs: [60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/vulture/hurt.png`, frames: 10, frameMs: [80, 60, 40, 20, 400, 40, 40, 60, 40, 20], loop: false },
      death: { url: `${B}/vulture/death.png`, frames: 10, frameMs: [80, 40, 40, 60, 40, 300, 60, 40, 20, 120], loop: false },
    },
  },
  desert_lizard: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/desert_lizard/walk.png`, frames: 11, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/desert_lizard/hurt.png`, frames: 9, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/desert_lizard/death.png`, frames: 11, frameMs: [100, 50, 50, 50, 50, 60, 60, 60, 40, 40, 120], loop: false },
    },
  },
  jackal: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/jackal/walk.png`, frames: 16, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/jackal/hurt.png`, frames: 12, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/jackal/death.png`, frames: 29, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
    },
  },
  kalphite_worker: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/kalphite_worker/walk.png`, frames: 15, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/kalphite_worker/hurt.png`, frames: 32, frameMs: [80, 60, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60], loop: false },
      death: { url: `${B}/kalphite_worker/death.png`, frames: 44, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 60, 30, 30, 60, 30, 30, 60, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
    },
  },
  scarab_mage: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/scarab_mage/walk.png`, frames: 15, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/scarab_mage/hurt.png`, frames: 18, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 400, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/scarab_mage/death.png`, frames: 18, frameMs: [160, 40, 40, 40, 40, 40, 40, 56, 56, 56, 56, 56, 40, 40, 60, 60, 60, 120], loop: false },
    },
  },
  mummy: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/mummy/walk.png`, frames: 16, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/mummy/hurt.png`, frames: 30, frameMs: [120, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 40, 40, 40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/mummy/death.png`, frames: 38, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 120], loop: false },
    },
  },
  locust_rider: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/locust_rider/walk.png`, frames: 16, frameMs: [80, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 40, 40], loop: true },
      hurt: { url: `${B}/locust_rider/hurt.png`, frames: 23, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 50, 50, 50, 50, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/locust_rider/death.png`, frames: 14, frameMs: [120, 40, 40, 60, 60, 50, 50, 50, 50, 50, 50, 50, 50, 120], loop: false },
    },
  },
  dust_devil: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/dust_devil/walk.png`, frames: 21, frameMs: [120, 47, 47, 47, 50, 50, 50, 50, 50, 50, 60, 60, 47, 47, 47, 53, 53, 53, 47, 47, 47], loop: true },
      hurt: { url: `${B}/dust_devil/hurt.png`, frames: 28, frameMs: [80, 40, 40, 60, 60, 47, 47, 47, 53, 53, 53, 60, 60, 60, 53, 53, 53, 50, 50, 30, 30, 53, 53, 53, 60, 60, 60, 60], loop: false },
      death: { url: `${B}/dust_devil/death.png`, frames: 10, frameMs: [100, 50, 50, 50, 50, 50, 50, 60, 60, 120], loop: false },
    },
  },
  kalphite_guardian: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/kalphite_guardian/walk.png`, frames: 16, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60], loop: true },
      hurt: { url: `${B}/kalphite_guardian/hurt.png`, frames: 32, frameMs: [80, 60, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60], loop: false },
      death: { url: `${B}/kalphite_guardian/death.png`, frames: 75, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 60, 60, 60, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 30, 30, 60, 60, 60, 30, 30, 60, 60, 60, 60, 30, 30], loop: false },
    },
  },
  kbd: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/kbd/walk.png`, frames: 31, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/kbd/hurt.png`, frames: 21, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 400, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/kbd/death.png`, frames: 30, frameMs: [60, 40, 40, 50, 50, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 50, 50, 50, 50], loop: false },
      breath: { url: `${B}/kbd/breath.png`, frames: 37, frameMs: [40, 40, 50, 50, 40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60], loop: false },
    },
  },
  corporeal_beast: {
    frameW: 256, frameH: 256,
    clips: {
      walk: { url: `${B}/corporeal_beast/walk.png`, frames: 33, frameMs: [200, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/corporeal_beast/hurt.png`, frames: 23, frameMs: [160, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/corporeal_beast/death.png`, frames: 35, frameMs: [180, 53, 53, 53, 50, 50, 47, 47, 47, 47, 47, 47, 60, 60, 60, 60, 40, 40, 340, 60, 60, 60, 60, 60, 60, 60, 50, 50, 50, 50, 320, 55, 55, 55, 55], loop: false },
    },
  },
  dark_core: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/dark_core/walk.png`, frames: 15, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      death: { url: `${B}/dark_core/death.png`, frames: 34, frameMs: [100, 50, 50, 50, 50, 50, 50, 40, 40, 40, 40, 40, 40, 60, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 60, 60, 60, 60, 60, 60, 60, 60], loop: false },
    },
  },
  graardor: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/graardor/walk.png`, frames: 31, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: true },
      hurt: { url: `${B}/graardor/hurt.png`, frames: 21, frameMs: [80, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40], loop: false },
      death: { url: `${B}/graardor/death.png`, frames: 49, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 30, 30, 60, 60, 30, 30, 60, 60, 60, 120], loop: false },
    },
  },
  steelwill: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/steelwill/walk.png`, frames: 17, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/steelwill/hurt.png`, frames: 25, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/steelwill/death.png`, frames: 46, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  strongstack: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/strongstack/walk.png`, frames: 17, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/strongstack/hurt.png`, frames: 25, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/strongstack/death.png`, frames: 46, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
  grimspike: {
    frameW: 128, frameH: 128,
    clips: {
      walk: { url: `${B}/grimspike/walk.png`, frames: 17, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: true },
      hurt: { url: `${B}/grimspike/hurt.png`, frames: 25, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
      death: { url: `${B}/grimspike/death.png`, frames: 46, frameMs: [100, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50], loop: false },
    },
  },
};
