// AUTO-GENERATED by scripts/render-osrs-spotanims.mjs + scripts/generate-spotanims-data.mjs.
// Do not edit by hand — re-bake and regenerate. 73 sheets.
// Raw sheet facts for every baked spotanim (GFX) sprite sheet; presentation
// (draw size, speed, blend, loop) is layered on in lib/game/data/spotanims.ts.

export interface SpotAnimSheet {
  url: string;
  frames: number;
  frameW: number;
  frameH: number;
  /** Authentic per-frame durations (ms) from the cache sequence. */
  frameMs: number[];
}

const B = `${process.env.NEXT_PUBLIC_BASE_PATH || ''}/assets/spotanims`;

export const SPOTANIM_SHEETS: Record<string, SpotAnimSheet> = {
  hit_air_1: { url: `${B}/hit_air_1.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_air_2: { url: `${B}/hit_air_2.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_air_3: { url: `${B}/hit_air_3.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_air_4: { url: `${B}/hit_air_4.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_air_5: { url: `${B}/hit_air_5.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_blood_1: { url: `${B}/hit_blood_1.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [20, 80, 80, 80, 80, 20, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80] },
  hit_blood_2: { url: `${B}/hit_blood_2.png`, frames: 10, frameW: 96, frameH: 96, frameMs: [20, 60, 60, 60, 40, 40, 40, 60, 60, 60] },
  hit_blood_3: { url: `${B}/hit_blood_3.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [20, 80, 80, 80, 80, 20, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80] },
  hit_blood_4: { url: `${B}/hit_blood_4.png`, frames: 14, frameW: 96, frameH: 96, frameMs: [20, 80, 80, 80, 60, 60, 60, 80, 80, 80, 80, 80, 120, 140] },
  hit_earth_1: { url: `${B}/hit_earth_1.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_earth_2: { url: `${B}/hit_earth_2.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_earth_3: { url: `${B}/hit_earth_3.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_earth_4: { url: `${B}/hit_earth_4.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_earth_5: { url: `${B}/hit_earth_5.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_fire_1: { url: `${B}/hit_fire_1.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_fire_2: { url: `${B}/hit_fire_2.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_fire_3: { url: `${B}/hit_fire_3.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_fire_4: { url: `${B}/hit_fire_4.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_fire_5: { url: `${B}/hit_fire_5.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_ice_1: { url: `${B}/hit_ice_1.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  hit_ice_2: { url: `${B}/hit_ice_2.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  hit_ice_3: { url: `${B}/hit_ice_3.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_ice_4: { url: `${B}/hit_ice_4.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [60, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80] },
  hit_shadow_1: { url: `${B}/hit_shadow_1.png`, frames: 14, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 80, 120, 80, 80] },
  hit_shadow_2: { url: `${B}/hit_shadow_2.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [20, 60, 120, 140, 140, 140, 60, 60, 60, 60, 140, 140, 140, 120, 60, 20] },
  hit_shadow_3: { url: `${B}/hit_shadow_3.png`, frames: 14, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 80, 120, 80, 80] },
  hit_shadow_4: { url: `${B}/hit_shadow_4.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [20, 120, 120, 160, 140, 140, 120, 40, 40, 120, 140, 140, 160, 120, 120, 20] },
  hit_smoke_1: { url: `${B}/hit_smoke_1.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 40, 60, 80, 80, 80, 100, 100, 100, 80] },
  hit_smoke_2: { url: `${B}/hit_smoke_2.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  hit_smoke_3: { url: `${B}/hit_smoke_3.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 40, 60, 80, 80, 80, 100, 100, 100, 80] },
  hit_smoke_4: { url: `${B}/hit_smoke_4.png`, frames: 16, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  hit_water_1: { url: `${B}/hit_water_1.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_water_2: { url: `${B}/hit_water_2.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_water_3: { url: `${B}/hit_water_3.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_water_4: { url: `${B}/hit_water_4.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_water_5: { url: `${B}/hit_water_5.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  portal: { url: `${B}/portal.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80] },
  proj_air_1: { url: `${B}/proj_air_1.png`, frames: 4, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40] },
  proj_air_2: { url: `${B}/proj_air_2.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_air_3: { url: `${B}/proj_air_3.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 60] },
  proj_air_4: { url: `${B}/proj_air_4.png`, frames: 3, frameW: 96, frameH: 96, frameMs: [40, 40, 40] },
  proj_air_5: { url: `${B}/proj_air_5.png`, frames: 3, frameW: 96, frameH: 96, frameMs: [40, 40, 40] },
  proj_blood_1: { url: `${B}/proj_blood_1.png`, frames: 11, frameW: 96, frameH: 96, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20] },
  proj_blood_2: { url: `${B}/proj_blood_2.png`, frames: 11, frameW: 96, frameH: 96, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20] },
  proj_blood_3: { url: `${B}/proj_blood_3.png`, frames: 11, frameW: 96, frameH: 96, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20] },
  proj_blood_4: { url: `${B}/proj_blood_4.png`, frames: 11, frameW: 96, frameH: 96, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20] },
  proj_earth_1: { url: `${B}/proj_earth_1.png`, frames: 4, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40] },
  proj_earth_2: { url: `${B}/proj_earth_2.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_earth_3: { url: `${B}/proj_earth_3.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 60] },
  proj_earth_4: { url: `${B}/proj_earth_4.png`, frames: 3, frameW: 96, frameH: 96, frameMs: [40, 40, 40] },
  proj_earth_5: { url: `${B}/proj_earth_5.png`, frames: 3, frameW: 96, frameH: 96, frameMs: [40, 40, 40] },
  proj_fire_1: { url: `${B}/proj_fire_1.png`, frames: 4, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40] },
  proj_fire_2: { url: `${B}/proj_fire_2.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_fire_3: { url: `${B}/proj_fire_3.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 60] },
  proj_fire_4: { url: `${B}/proj_fire_4.png`, frames: 3, frameW: 96, frameH: 96, frameMs: [40, 40, 40] },
  proj_fire_5: { url: `${B}/proj_fire_5.png`, frames: 3, frameW: 96, frameH: 96, frameMs: [40, 40, 40] },
  proj_ice_1: { url: `${B}/proj_ice_1.png`, frames: 9, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_ice_2: { url: `${B}/proj_ice_2.png`, frames: 9, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_ice_3: { url: `${B}/proj_ice_3.png`, frames: 9, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_ice_4: { url: `${B}/proj_ice_4.png`, frames: 9, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_shadow_1: { url: `${B}/proj_shadow_1.png`, frames: 7, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60] },
  proj_shadow_2: { url: `${B}/proj_shadow_2.png`, frames: 7, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60] },
  proj_shadow_3: { url: `${B}/proj_shadow_3.png`, frames: 5, frameW: 96, frameH: 96, frameMs: [20, 80, 80, 80, 80] },
  proj_shadow_4: { url: `${B}/proj_shadow_4.png`, frames: 5, frameW: 96, frameH: 96, frameMs: [20, 80, 80, 80, 80] },
  proj_smoke_1: { url: `${B}/proj_smoke_1.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_smoke_2: { url: `${B}/proj_smoke_2.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_smoke_3: { url: `${B}/proj_smoke_3.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_smoke_4: { url: `${B}/proj_smoke_4.png`, frames: 12, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_water_1: { url: `${B}/proj_water_1.png`, frames: 4, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40] },
  proj_water_2: { url: `${B}/proj_water_2.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_water_3: { url: `${B}/proj_water_3.png`, frames: 8, frameW: 96, frameH: 96, frameMs: [60, 60, 60, 60, 60, 60, 60, 60] },
  proj_water_4: { url: `${B}/proj_water_4.png`, frames: 3, frameW: 96, frameH: 96, frameMs: [40, 40, 40] },
  proj_water_5: { url: `${B}/proj_water_5.png`, frames: 3, frameW: 96, frameH: 96, frameMs: [40, 40, 40] },
};
