// AUTO-GENERATED by scripts/render-osrs-spotanims.mjs + scripts/generate-spotanims-data.mjs.
// Do not edit by hand — re-bake and regenerate. 81 sheets.
// Raw sheet facts for every baked spotanim (GFX) sprite sheet; presentation
// (draw size, speed, blend, loop) is layered on in lib/game/data/spotanims.ts.

export interface SpotAnimSheet {
  url: string;
  frames: number;
  frameW: number;
  frameH: number;
  /** Authentic per-frame durations (ms) from the cache sequence. */
  frameMs: number[];
  /** The cell's side in model units, when the bake recorded it. */
  worldCell?: number;
}

const B = `${process.env.NEXT_PUBLIC_BASE_PATH || ''}/assets/spotanims`;

export const SPOTANIM_SHEETS: Record<string, SpotAnimSheet> = {
  cast_death_charge: { url: `${B}/cast_death_charge.png?v=37acbb59`, frames: 14, frameW: 192, frameH: 192, frameMs: [100, 100, 80, 80, 80, 120, 80, 80, 80, 80, 80, 60, 60, 40] },
  hit_air_1: { url: `${B}/hit_air_1.png?v=5fb0bc15`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_air_2: { url: `${B}/hit_air_2.png?v=f2a7b24a`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_air_3: { url: `${B}/hit_air_3.png?v=2fa21224`, frames: 12, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_air_4: { url: `${B}/hit_air_4.png?v=74551fb4`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_air_5: { url: `${B}/hit_air_5.png?v=74551fb4`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_blood_1: { url: `${B}/hit_blood_1.png?v=644adbd6`, frames: 16, frameW: 192, frameH: 192, frameMs: [20, 80, 80, 80, 80, 20, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80] },
  hit_blood_2: { url: `${B}/hit_blood_2.png?v=fc62c5a9`, frames: 10, frameW: 192, frameH: 192, frameMs: [20, 60, 60, 60, 40, 40, 40, 60, 60, 60] },
  hit_blood_3: { url: `${B}/hit_blood_3.png?v=3843666d`, frames: 16, frameW: 192, frameH: 192, frameMs: [20, 80, 80, 80, 80, 20, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80] },
  hit_blood_4: { url: `${B}/hit_blood_4.png?v=27b7faae`, frames: 14, frameW: 192, frameH: 192, frameMs: [20, 80, 80, 80, 60, 60, 60, 80, 80, 80, 80, 80, 120, 140] },
  hit_earth_1: { url: `${B}/hit_earth_1.png?v=278c69bf`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_earth_2: { url: `${B}/hit_earth_2.png?v=ef9616ab`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_earth_3: { url: `${B}/hit_earth_3.png?v=dc393147`, frames: 12, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_earth_4: { url: `${B}/hit_earth_4.png?v=38d112da`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_earth_5: { url: `${B}/hit_earth_5.png?v=38d112da`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_fire_1: { url: `${B}/hit_fire_1.png?v=f95f1e61`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_fire_2: { url: `${B}/hit_fire_2.png?v=ee0787eb`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_fire_3: { url: `${B}/hit_fire_3.png?v=bd6b2f02`, frames: 12, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_fire_4: { url: `${B}/hit_fire_4.png?v=886e829b`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_fire_5: { url: `${B}/hit_fire_5.png?v=886e829b`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_ice_1: { url: `${B}/hit_ice_1.png?v=7aa361c5`, frames: 16, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  hit_ice_2: { url: `${B}/hit_ice_2.png?v=7268a18e`, frames: 16, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  hit_ice_3: { url: `${B}/hit_ice_3.png?v=9f8e3bae`, frames: 16, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_ice_4: { url: `${B}/hit_ice_4.png?v=034f8a19`, frames: 16, frameW: 192, frameH: 192, frameMs: [60, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80] },
  hit_shadow_1: { url: `${B}/hit_shadow_1.png?v=e67019ca`, frames: 14, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 80, 120, 80, 80] },
  hit_shadow_2: { url: `${B}/hit_shadow_2.png?v=fceb3100`, frames: 16, frameW: 192, frameH: 192, frameMs: [20, 60, 120, 140, 140, 140, 60, 60, 60, 60, 140, 140, 140, 120, 60, 20] },
  hit_shadow_3: { url: `${B}/hit_shadow_3.png?v=643423f6`, frames: 14, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 80, 120, 80, 80] },
  hit_shadow_4: { url: `${B}/hit_shadow_4.png?v=8ea3bb00`, frames: 16, frameW: 192, frameH: 192, frameMs: [20, 120, 120, 160, 140, 140, 120, 40, 40, 120, 140, 140, 160, 120, 120, 20] },
  hit_smoke_1: { url: `${B}/hit_smoke_1.png?v=21e482b6`, frames: 16, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 40, 60, 80, 80, 80, 100, 100, 100, 80] },
  hit_smoke_2: { url: `${B}/hit_smoke_2.png?v=79759e63`, frames: 16, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  hit_smoke_3: { url: `${B}/hit_smoke_3.png?v=5b9d9d54`, frames: 16, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 40, 60, 80, 80, 80, 100, 100, 100, 80] },
  hit_smoke_4: { url: `${B}/hit_smoke_4.png?v=d731eb5f`, frames: 16, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  hit_water_1: { url: `${B}/hit_water_1.png?v=22d6677b`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_water_2: { url: `${B}/hit_water_2.png?v=f117b323`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  hit_water_3: { url: `${B}/hit_water_3.png?v=5be55009`, frames: 12, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60] },
  hit_water_4: { url: `${B}/hit_water_4.png?v=3fa74fa7`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  hit_water_5: { url: `${B}/hit_water_5.png?v=3fa74fa7`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 60, 60, 60, 60, 60, 60, 60] },
  ice_shard: { url: `${B}/ice_shard.png?v=fd33cbdf`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  lobby_torch: { url: `${B}/lobby_torch.png?v=317e0c78`, frames: 18, frameW: 256, frameH: 256, frameMs: [100, 100, 100, 100, 100, 100, 100, 100, 120, 100, 100, 100, 100, 100, 100, 100, 100, 100], worldCell: 352 },
  portal: { url: `${B}/portal.png?v=0369a534`, frames: 12, frameW: 192, frameH: 192, frameMs: [80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80] },
  proj_air_1: { url: `${B}/proj_air_1.png?v=380dfc30`, frames: 4, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40] },
  proj_air_2: { url: `${B}/proj_air_2.png?v=575b2d47`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_air_3: { url: `${B}/proj_air_3.png?v=b2d39f72`, frames: 8, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 60] },
  proj_air_4: { url: `${B}/proj_air_4.png?v=b5b06f3f`, frames: 3, frameW: 192, frameH: 192, frameMs: [40, 40, 40] },
  proj_air_5: { url: `${B}/proj_air_5.png?v=af7405bf`, frames: 3, frameW: 192, frameH: 192, frameMs: [40, 40, 40] },
  proj_blood_1: { url: `${B}/proj_blood_1.png?v=083cd57c`, frames: 11, frameW: 192, frameH: 192, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20] },
  proj_blood_2: { url: `${B}/proj_blood_2.png?v=083cd57c`, frames: 11, frameW: 192, frameH: 192, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20] },
  proj_blood_3: { url: `${B}/proj_blood_3.png?v=6d67b037`, frames: 11, frameW: 192, frameH: 192, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20] },
  proj_blood_4: { url: `${B}/proj_blood_4.png?v=6d67b037`, frames: 11, frameW: 192, frameH: 192, frameMs: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20] },
  proj_dragonfire: { url: `${B}/proj_dragonfire.png?v=3c6856a1`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_dragonfire_ice: { url: `${B}/proj_dragonfire_ice.png?v=23685a08`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_dragonfire_poison: { url: `${B}/proj_dragonfire_poison.png?v=5a22c8ce`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_dragonfire_shock: { url: `${B}/proj_dragonfire_shock.png?v=212234b2`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_earth_1: { url: `${B}/proj_earth_1.png?v=4f89926b`, frames: 4, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40] },
  proj_earth_2: { url: `${B}/proj_earth_2.png?v=fc590c87`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_earth_3: { url: `${B}/proj_earth_3.png?v=18c27552`, frames: 8, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 60] },
  proj_earth_4: { url: `${B}/proj_earth_4.png?v=e4a74140`, frames: 3, frameW: 192, frameH: 192, frameMs: [40, 40, 40] },
  proj_earth_5: { url: `${B}/proj_earth_5.png?v=4c67be0b`, frames: 3, frameW: 192, frameH: 192, frameMs: [40, 40, 40] },
  proj_fire_1: { url: `${B}/proj_fire_1.png?v=a9e0aab1`, frames: 4, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40] },
  proj_fire_2: { url: `${B}/proj_fire_2.png?v=6584d496`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_fire_3: { url: `${B}/proj_fire_3.png?v=5f88eae2`, frames: 8, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 60] },
  proj_fire_4: { url: `${B}/proj_fire_4.png?v=240595a5`, frames: 3, frameW: 192, frameH: 192, frameMs: [40, 40, 40] },
  proj_fire_5: { url: `${B}/proj_fire_5.png?v=6d0b8707`, frames: 3, frameW: 192, frameH: 192, frameMs: [40, 40, 40] },
  proj_graardor: { url: `${B}/proj_graardor.png?v=c6f19b07`, frames: 4, frameW: 192, frameH: 192, frameMs: [100, 100, 100, 100] },
  proj_ice_1: { url: `${B}/proj_ice_1.png?v=c6bdcb78`, frames: 9, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_ice_2: { url: `${B}/proj_ice_2.png?v=c62b9341`, frames: 9, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_ice_3: { url: `${B}/proj_ice_3.png?v=c6bdcb78`, frames: 9, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_ice_4: { url: `${B}/proj_ice_4.png?v=c6bdcb78`, frames: 9, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_shadow_1: { url: `${B}/proj_shadow_1.png?v=73aa9d1b`, frames: 7, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60] },
  proj_shadow_2: { url: `${B}/proj_shadow_2.png?v=73aa9d1b`, frames: 7, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60] },
  proj_shadow_3: { url: `${B}/proj_shadow_3.png?v=025197ef`, frames: 5, frameW: 192, frameH: 192, frameMs: [20, 80, 80, 80, 80] },
  proj_shadow_4: { url: `${B}/proj_shadow_4.png?v=025197ef`, frames: 5, frameW: 192, frameH: 192, frameMs: [20, 80, 80, 80, 80] },
  proj_smoke_1: { url: `${B}/proj_smoke_1.png?v=464d4b0e`, frames: 12, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_smoke_2: { url: `${B}/proj_smoke_2.png?v=464d4b0e`, frames: 12, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_smoke_3: { url: `${B}/proj_smoke_3.png?v=6a79cdc3`, frames: 12, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_smoke_4: { url: `${B}/proj_smoke_4.png?v=6a79cdc3`, frames: 12, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40] },
  proj_water_1: { url: `${B}/proj_water_1.png?v=b2ba5171`, frames: 4, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40] },
  proj_water_2: { url: `${B}/proj_water_2.png?v=5076927d`, frames: 8, frameW: 192, frameH: 192, frameMs: [40, 40, 40, 40, 40, 40, 40, 40] },
  proj_water_3: { url: `${B}/proj_water_3.png?v=d616d80b`, frames: 8, frameW: 192, frameH: 192, frameMs: [60, 60, 60, 60, 60, 60, 60, 60] },
  proj_water_4: { url: `${B}/proj_water_4.png?v=a4d9cf9f`, frames: 3, frameW: 192, frameH: 192, frameMs: [40, 40, 40] },
  proj_water_5: { url: `${B}/proj_water_5.png?v=fe18da4e`, frames: 3, frameW: 192, frameH: 192, frameMs: [40, 40, 40] },
};
